[package]
name = "gateway-contracts-v1"
description = "Gateway Contracts - V1"
version = "0.1.0"
authors = ["Perry Birch <perrybirch@vizidrix.com>"]
publish = false

[dependencies]
serde = "1.0"
serde_derive = "1.0.101"

[dev-dependencies]
serde_json = "1.0"